name: midjourney_client
description: Unofficial midjourney client that gives you possibility to generates images!
version: 0.0.1
repository: https://github.com/hawkkiller/midjourney-client

environment:
  sdk: ^3.0.0

dependencies:
  l: ^4.0.1

dev_dependencies:
  sizzle_lints: 1.0.10
  test: ^1.21.0
